classdef caloriemeter_matlab < matlab.apps.AppBase

    % Properties that correspond to app components
    properties (Access = public)
        UIFigure                       matlab.ui.Figure
        CalculateButton                matlab.ui.control.Button
        TotalCaloriesConsumedInADayEditField  matlab.ui.control.NumericEditField
        TotalCaloriesConsumedInADayEditFieldLabel  matlab.ui.control.Label
        DinnerPanel                    matlab.ui.container.Panel
        ServingsLabel_4                matlab.ui.control.Label
        ItemsLabel_4                   matlab.ui.control.Label
        ShahipaneerCheckBox            matlab.ui.control.CheckBox
        MultiplierEditField_40         matlab.ui.control.NumericEditField
        PaalakPannerCheckBox           matlab.ui.control.CheckBox
        MultiplierEditField_39         matlab.ui.control.NumericEditField
        ChapatiCheckBox_2              matlab.ui.control.CheckBox
        MultiplierEditField_38         matlab.ui.control.NumericEditField
        TandooriNanCheckBox            matlab.ui.control.CheckBox
        MultiplierEditField_37         matlab.ui.control.NumericEditField
        DaalCheckBox_2                 matlab.ui.control.CheckBox
        MultiplierEditField_36         matlab.ui.control.NumericEditField
        MixVegCuriCheckBox             matlab.ui.control.CheckBox
        MultiplierEditField_35         matlab.ui.control.NumericEditField
        FriedRiceCheckBox              matlab.ui.control.CheckBox
        MultiplierEditField_34         matlab.ui.control.NumericEditField
        CurdCheckBox                   matlab.ui.control.CheckBox
        MultiplierEditField_33         matlab.ui.control.NumericEditField
        JeeraRiceCheckBox              matlab.ui.control.CheckBox
        MultiplierEditField_32         matlab.ui.control.NumericEditField
        MultiplierEditField_31         matlab.ui.control.NumericEditField
        TotalCaloriesEditField_4       matlab.ui.control.NumericEditField
        TotalCaloriesEditField_4Label  matlab.ui.control.Label
        CalculateForDinnerButton       matlab.ui.control.Button
        TomatoRiceCheckBox             matlab.ui.control.CheckBox
        SnacksPanel                    matlab.ui.container.Panel
        ServingsLabel_3                matlab.ui.control.Label
        ItemsLabel_3                   matlab.ui.control.Label
        PaniPuriCheckBox               matlab.ui.control.CheckBox
        MultiplierEditField_30         matlab.ui.control.NumericEditField
        PaneerRollCheckBox             matlab.ui.control.CheckBox
        MultiplierEditField_29         matlab.ui.control.NumericEditField
        GreenTeaCheckBox               matlab.ui.control.CheckBox
        MultiplierEditField_28         matlab.ui.control.NumericEditField
        SamossaCheckBox                matlab.ui.control.CheckBox
        MultiplierEditField_27         matlab.ui.control.NumericEditField
        ChipsCheckBox                  matlab.ui.control.CheckBox
        MultiplierEditField_26         matlab.ui.control.NumericEditField
        ColdDrinksCheckBox             matlab.ui.control.CheckBox
        MultiplierEditField_25         matlab.ui.control.NumericEditField
        TeaCheckBox                    matlab.ui.control.CheckBox
        MultiplierEditField_24         matlab.ui.control.NumericEditField
        CoffeeCheckBox                 matlab.ui.control.CheckBox
        MultiplierEditField_23         matlab.ui.control.NumericEditField
        EggSandwichCheckBox            matlab.ui.control.CheckBox
        MultiplierEditField_22         matlab.ui.control.NumericEditField
        MultiplierEditField_21         matlab.ui.control.NumericEditField
        TotalCaloriesEditField_3       matlab.ui.control.NumericEditField
        TotalCaloriesEditField_3Label  matlab.ui.control.Label
        CalculateForSnacksButton       matlab.ui.control.Button
        SandwichCheckBox               matlab.ui.control.CheckBox
        LunchPanel                     matlab.ui.container.Panel
        ServingsLabel_2                matlab.ui.control.Label
        ItemsLabel_2                   matlab.ui.control.Label
        BiryaniCheckBox                matlab.ui.control.CheckBox
        MultiplierEditField_20         matlab.ui.control.NumericEditField
        PaneerButterMasalaCheckBox     matlab.ui.control.CheckBox
        MultiplierEditField_19         matlab.ui.control.NumericEditField
        TandooriNaanCheckBox           matlab.ui.control.CheckBox
        MultiplierEditField_18         matlab.ui.control.NumericEditField
        DaalCheckBox                   matlab.ui.control.CheckBox
        MultiplierEditField_17         matlab.ui.control.NumericEditField
        DaalFryCheckBox                matlab.ui.control.CheckBox
        MultiplierEditField_16         matlab.ui.control.NumericEditField
        RiceCheckBox                   matlab.ui.control.CheckBox
        MultiplierEditField_15         matlab.ui.control.NumericEditField
        AlooParathaCheckBox            matlab.ui.control.CheckBox
        MultiplierEditField_14         matlab.ui.control.NumericEditField
        ChapatiCheckBox                matlab.ui.control.CheckBox
        MultiplierEditField_13         matlab.ui.control.NumericEditField
        PaneerParathaCheckBox          matlab.ui.control.CheckBox
        MultiplierEditField_12         matlab.ui.control.NumericEditField
        MultiplierEditField_11         matlab.ui.control.NumericEditField
        TotalCaloriesEditField_2       matlab.ui.control.NumericEditField
        TotalCaloriesEditField_2Label  matlab.ui.control.Label
        CalculateForLunchButton        matlab.ui.control.Button
        ParathaCheckBox                matlab.ui.control.CheckBox
        BreakfastPanel                 matlab.ui.container.Panel
        ServingsLabel                  matlab.ui.control.Label
        ItemsLabel                     matlab.ui.control.Label
        AppleCheckBox                  matlab.ui.control.CheckBox
        MultiplierEditField_10         matlab.ui.control.NumericEditField
        BananaCheckBox                 matlab.ui.control.CheckBox
        MultiplierEditField_9          matlab.ui.control.NumericEditField
        UpmaCheckBox                   matlab.ui.control.CheckBox
        MultiplierEditField_8          matlab.ui.control.NumericEditField
        PohaCheckBox_2                 matlab.ui.control.CheckBox
        MultiplierEditField_7          matlab.ui.control.NumericEditField
        UttapamCheckBox                matlab.ui.control.CheckBox
        MultiplierEditField_6          matlab.ui.control.NumericEditField
        PomegranateCheckBox            matlab.ui.control.CheckBox
        MultiplierEditField_5          matlab.ui.control.NumericEditField
        DosaCheckBox                   matlab.ui.control.CheckBox
        MultiplierEditField_4          matlab.ui.control.NumericEditField
        VadaCheckBox                   matlab.ui.control.CheckBox
        MultiplierEditField_3          matlab.ui.control.NumericEditField
        SambharCheckBox                matlab.ui.control.CheckBox
        MultiplierEditField_2          matlab.ui.control.NumericEditField
        MultiplierEditField            matlab.ui.control.NumericEditField
        TotalCaloriesEditField         matlab.ui.control.NumericEditField
        TotalCaloriesEditFieldLabel    matlab.ui.control.Label
        CalculateForBreakfastButton    matlab.ui.control.Button
        IdliCheckBox                   matlab.ui.control.CheckBox
        CaloriemeterLabel              matlab.ui.control.Label
    end
    
